source 'https://github.com/CocoaPods/Specs.git'

target 'BonjourDevAPIFinder', :exclusive => true do
  pod "BonjourDevAPIFinder", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "BonjourDevAPIFinder", :path => "../"

  
end
